name = str(input("Enter your name: "))
Age = int(input("Enter your age: "))
Experience = int(input("Enter your years of experience: "))
CurrentSalary = float(input("Enter your current salary: "))
DesiredSalary = float(input("Enter your desired salary: "))
SalaryDifference = (DesiredSalary - CurrentSalary)
RequiredIncrease = ((SalaryDifference / (CurrentSalary)) * 100)

print("Name:", name)
print("Age:", Age)
print("Experience:", Experience)
print("Current Salary:", CurrentSalary)
print("Desired Salary:", DesiredSalary)
print("Salary Difference:", SalaryDifference)
print("Required Increase:", RequiredIncrease, "%")